### ISSUE TITLE
Rework Homepage Content 1

### ISSUE THREAD

**Issue by JohannesBraunbruckSYNYO** [dataobservatory-eu/openmuse.dataobservatory.eu#10]
*_Change OpenMusE Logo to_ “OpenMuse-Logo-(600x600)transp”

_Change Title:_
**Open Music Europe (OpenMusE)** 
An open, scalable data-to-policy pipeline for European Music Ecosystems

_Insert content_:
**Background/Idea**
OpenMusE brings together music industry stakeholders and researchers from 11 EU countries and Ukraine. Our consortium recognises that placing European music ecosystems on a more competitive, fair, and sustainable footing requires evidence-based policymaking, business planning and accuracy. We provide the data needed for these actions. 

Using transparent methods and tools, OpenMusE maps the policy as well as the data landscape. The project bridges data gaps and empowers stakeholders and policymakers to take data-driven actions. Our project is grounded on principles of open policy analysis, open science, and open-source software development. We work with stakeholders to identify data gaps on the EU, national, and regional levels; co-create indicators and methods for bridging them; develop free software tools for data collection and analysis; and report our findings and every step taken to reach them. 

Using the OMO and our open-source software, music MSMEs without technical departments or expertise will be able to access and analyse open data; model volume and value, including of zero-price uses; create better business models; and generate corporate social responsibility and sustainability reports; all at a fraction of current costs. We validate these tools in four pilot studies that will bring concrete benefits to stakeholders within the project lifespan.

**Comment by JohannesBraunbruckSYNYO** [comment]
Please see as example



![Image](https://user-images.githubusercontent.com/121010544/224318121-f73e0fb2-fe39-4bbf-9cf8-ece70b17d09f.png)

**Comment by antaldaniel** [comment]
This is the new content/author/admin/_index.md

**Comment by JohannesBraunbruckSYNYO** [comment]
Where were these changes agreed upon?
As per my last mail, (23. Feb., 13:14) I wrote you that "the official name of the project (“An open, scalable data-to-policy pipeline for European music ecosystems”) and the acronym (“OpenMusE”) have to be present on all our official dissemination materials and the project website. "
If you want to have it any other way, you will have to discuss this with SINUS - who by my recollection did also not agree on this.

In that regard, please use 
Open Music Europe (OpenMusE)
An open, scalable data-to-policy pipeline for European Music Ecosystems
as requested.

**Comment by antaldaniel** [comment]
It's done.
