### ISSUE TITLE
Add Disclaimer

### ISSUE THREAD

**Issue by JohannesBraunbruckSYNYO** [dataobservatory-eu/openmuse.dataobservatory.eu#13]
_In the Footer of the Page please add:_

_To the left:_

Top left: add logo _OpenMuse-Logo-(600x600)transp_

_Below:_
Funded by the European Union. Views and opinions expressed are however those of the author(s) only and do not necessarily reflect those of the European Union or the European Research Executive Agency (REA). Neither the European Union nor the granting authority can be held responsible for them.
_Please add the Logo_ “EN_Co-Funded_by_the_EU_POS” on the left side

_In the middle_
**Contact Details**
SINUS MARKT- UND SOZIALFORSCHUNG GMBH
Adenauerplatz 1, Heidelberg 69115, Germany
JamesRhys.Edwards@sinus-institut.de

Below:
_Please add social Media Buttons and links that you already have_

Visual example: 

![Image](https://user-images.githubusercontent.com/121010544/224319548-41966a56-ca67-4293-ba27-803daf9b930d.png)

**Comment by antaldaniel** [comment]
Check the bottom of the website.

**Comment by JohannesBraunbruckSYNYO** [comment]
Please like mentioned add 
-the Logo of the project, 
-the European Union
-Social Media Links
-a contact Page

**Comment by antaldaniel** [comment]
The social media links are on the front page, 
so is the logo, 
the contact page is working, but it is not connected to James's email address, that is something we need to set up with Sinus.
