### ISSUE TITLE
Ressources Page

### ISSUE THREAD

**Issue by JohannesBraunbruckSYNYO** [dataobservatory-eu/openmuse.dataobservatory.eu#16]
_add content:_

**Deliverables** 
D1.1 Economy of music in Europe: Methods and indicators
D1.2 Report on the European Music Economy
D1.3 Report on Music Data Improvement Initiatives
D2.1 Music diversity and circulation: Novel data collection methods and indicators
D2.2 Report on Music Diversity and Circulation in Europe
D3.1 Music, Society, and Citizenship: Novel data collection methods and indicators
D3.2 Report on Music, Society, and Citizenship in Europe 
D4.1 Open-source music data software ecosystem
D4.2 Report on Music Innovation & Technology in Europe
D4.3 Software Validation Report
D5.1 Open Music Observatory
D5.6 Policy Brief 1
D5.7 Policy Brief 2

_please also add a greyed out "Download PDF" placeholder to the right like displayed here:_
example:

![Image](https://user-images.githubusercontent.com/121010544/224322077-34a27d90-1216-475b-97c5-b66117c8bfb7.png)

**Comment by antaldaniel** [comment]
https://openmuse.dataobservatory.eu/resources/

**Comment by antaldaniel** [comment]
They are added, also with the folder where the deliverables, and their work in progress can be downloaded.
